version: '3.8'
services:
  cadvisor3:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor3
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /sys:/sys:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  prometheus_docker_exporter:
    image: prom/prometheus-docker-exporter
    container_name: prometheus-docker-exporter
    ports:
      - "9104:9104"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
  prometheus_data:
